### PR TITLE
Specialize the conversion between wchar_t* and Go string on Windows only

### LINKED ISSUE #6: winapi error #42
I get the following panic on Windows:
```
2023/06/22 18:05:46 panic was raised: winapi error #42, stack: goroutine 13 [running]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/inspera/inspera-launcher/util.Recover(0xc004ef1f18)
	C:/msys64/home/ababo/launcher/util/misc.go:25 +0x45
panic({0x7ff756f11260, 0x7ff756b473f0})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/sstallion/go-hid.wcstogo(0x299ba598490)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/wchar.go:73 +0x1a5
github.com/sstallion/go-hid.newDeviceInfo(0x299ba5a0480)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/hid.go:123 +0x45
github.com/sstallion/go-hid.Enumerate(0x0?, 0x0?, 0xc004ef1ce0)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/hid.go:148 +0x94
github.com/inspera/inspera-launcher/sentinel.hidDevices()
	C:/msys64/home/ababo/launcher/sentinel/hid.go:64 +0x51
github.com/inspera/inspera-launcher/sentinel.newHIDMonitor(0xc00029ea80, 0xc002b3c870?)
	C:/msys64/home/ababo/launcher/sentinel/hid.go:25 +0x71
github.com/inspera/inspera-launcher/sentinel.Start(0xc000672000, 0xc00029ea80, 0xc002b3c870)
	C:/msys64/home/ababo/launcher/sentinel/sentinel.go:37 +0xfc
main.start(0xc0000c6210)
	C:/msys64/home/ababo/launcher/main.go:231 +0x7aa
main.main.func1()
	C:/msys64/home/ababo/launcher/main.go:356 +0x45
created by main.main
	C:/msys64/home/ababo/launcher/main.go:354 +0xa45
```

### PR DESCRIPTION
**Pull request by koron**
This will fix #6

### CODE REVIEW

**Comment by sstallion** [comment]
@koron Thank you for your contribution! Could you provide a little more detail on the issue you're seeing? Changes look pretty good, though I do worry a little about some of casting being done (namely interchanging `wchar_t *` and `uint16_t *`, which can have different alignment. This might need some deeper changes to support native UTF-16.

**Comment by sstallion** [comment]
Thinking about this a little more, what would you think of just changing references to `*C.wchar_t` to `unsafe.Pointer`? We can keep the original names but that may be the safest way to avoid making assumptions about alignment.

**Comment by sstallion** [comment]
> The root cause of the problem is `C.wcstombs()` and `C.mbstowcs` can't treat Chinese/Japanese/Korean in Windows.
> It is hard to describe why those functions doesn't work,
> it's a complex factors (code page, encoding, c-runtime, compiler used by CGO...) involved to dealing CGO in Windows.

Gotcha. If you could add a comment to this effect and include a copyright header at the top, we should be good to go. Thanks again!

**Comment by koron** [comment]
I added comments and update the PR.
Please check it.

Thanks.

**Comment by sstallion** [comment]
Thanks @koron! I'll get this merged ASAP.

**Pull request merged**
